print("'You wake up in a cold, dark room.'")
input("Press enter to continue.")
print("'You wonder who you are'")
input("Press enter to continue.")
name=input("What is your name?")
print("'You remember that your name is",name)
input("Press enter to continue.")
print("'You see two doors in front of you. For a second you wonder how you can see the door in the darkness.'")
input("Press enter to continue.")
print("'A voice echoes in your head telling you to choose a door'")
input("Press enter to continue.")
right_left=input("You pick a door. Right or Left.")
if right_left=="Right":
    print("'You walk towards the door on your right'")
    input("Press enter to continue.")
    print("'After opening it you are greeted with the sight of a chest and a hole in the ground'")
    input("Press enter to continue.")
    print("'Do you want to open the chest?'")
    input("Press enter to continue.")
    print("Yes/No")
    answer=input("Choose either Yes or No")
    if answer=="Yes":
        print("'You open the chest'")
        input("Press enter to continue.")
        print("'You see a sword and a shield'")
        input("Press enter to continue.")
        print("'Do you take the objects?'")
        input("Press enter to continue.")
        answer2=input("Enter either Yes or No.")
        if answer2=="Yes":
            print("'You took the objects.'")
            input("Press enter to continue.")
            print("'You go to the hole on the ground.'")
            input("Press enter to continue.")
            print("Something told you to jump inside.")
            input("Press enter to continue.")
            print("'You jump in expecting to die.'")
            input("Press enter to continue.")
            print("'Instead you fall on something as soft as the clouds. You notice your surroundings.'")
            input("Press enter to continue.")
            print("'You were in a place that you envisioned heaven to look like. White fluffy clouds were billowing around you and the air felt calm.'")
            input("Press enter to continue.")
            print("'With a double take you notice a grotesque creature sleeping. Its bulbous and scaly body terrified you.'")
            input("Press enter to continue.")
            print("Nothing so ugly belonged in such a heaven.")
            input("Press enter to continue.")
            print("'Do you murder the creature?'")
            canswer=input("Choose either Yes or No.")
            if canswer=="Yes":
                print("'You manage to slay a poor harmless creature.'")
                input("Press enter to continue.")
                print("Would you really consider this winning", name, "?")
            else:
                print("'You chose the nonviolent way.'")
                input("Press enter to continue.")
                print("'You were murdered by the creature.'")
                input("Press enter to continue.")
                print("'You clearly lost." ,name, "'")
        else:
            print("'You didn't take the objects.'")
            input("Press enter to continue.")
            print("'You jump in expecting to die.'")
            input("Press enter to continue.")
            print("'Instead you fall on something as soft as the clouds. You notice your surroundings.'")
            input("Press enter to continue.")
            print("'You were in a place that you envisioned heaven to look like. White fluffy clouds were billowing around you and the air felt calm.'")
            input("Press enter to continue.")
            print("'With a double take you notice a grotesque creature sleeping. Its bulbous and scaly body terrified you.'")
            input("Press enter to continue.")
            print("'You tiptoe around the creature trying to not wake it up.'")
            input("Press enter to continue.")
            print("'The creature woke up and gave a large growl and advanced towards you.'")
            input("Press enter to continue.")
            print("'You are immediately killed by the creature.'")
            input("Press enter to continue.")
            print("'You need to reevaluate your life choices.'", name)
    else:
        print("'You don't open the chest.")
        input("Press enter to continue.")
        print("'You go down the hole despite it being a terrible choice.'")
        input("Press enter to continue.")
        print("'After jumping in you see a creature sleeping.")
        input("Press enter to continue.")
        print("'You are immediately killed by the creature.'")
        input("Press enter to continue.")
        print("'You need to reevaluate your life choices.'", name)
elif right_left=="Left":
    print("'You walk towards the door on your left.'")
    input("Press enter to continue.")
    print("'You open the door.'")
    input("Press enter to continue.")
    print("'You enter a room that is completely barren. You look around for a moment expecting something to pop up.'")
    input("Press enter to continue.")
    print("'Out of the corner of your eyes you can see a black cat appearing. You approach it.'")
    input("Press enter to continue.")
    print("'The cat yawned and somehow the creature spoke in your mind.'")
    input("Press enter to continue.")
    print("'Hello, how do you do?'")
    input("Press enter to continue.")
    print("'Before you can answer the cat continues.'")
    input("Press enter to continue.")
    print("Doesn't really matter, does it? Tell me, do you think your choice ultimately matters?'")
    input("Press enter to continue.")
    ans=input("Answer Yes or No.")
    if ans=="Yes":
        print("'If you are so sure then tell me will you take this coin?'")
        input("Press enter to continue.")
        print("'A coin appears in front of you floating in mid-air.'")
        input("Press enter to continue.")
        print("Do you take the coin?'")
        ans1=input("Amswer Yes or No.")
        if ans1=="Yes":
            print("'You reach for the coin in mid air and grab it.'")
            input("Press enter to continue.")
            print("'The coin felt warm in your hands. You turned it around to see your face stamped on it.'")
            input("Press enter to continue.")
            print("'This would help you pass in your journey.'")
            input("Press enter to continue.")
            print("'You look towards where the cat was but it vanished leaving a gaping hole where it was standing. You approached the hole, looking down.'")
            input("Press enter to continue.")
            print("'Below was pitch black.'")
            input("Press enter to continue.")
            print("'You feel a strange urge to jump. Ignoring all bounds in logic you jump.'")

            print("'You jump in. You end up splashing in a body of murky water. It smelled like sewage and you assumed it was.'")
            input("Press enter to continue.")
            print("'The water barely reached your knees. You waddled ahead looking for something besides endless water and darkness.'")
            input("Press enter to continue.")
            print("'All of a sudden you see a boat ahead of you.'")
            input("Press enter to continue.")
            print("'You scream trying to attract the attention of anyone on the boat.'")
            input("Press enter to continue.")
            print("'A robed figure came over to you with the boat.'")
            input("Press enter to continue.")
            print("'Do you have a coin?' The robed figure asks you.")
            input("Press enter to continue.")
            print("'You hand the coin to the figure.'")
            input("Press enter to continue.")
            print("'With a curt nod the figure reached out a boney hand and helped you climb the boat.'")
            input("Press enter to continue.")
            print("'You crossed the river with the robed figure.'")
            input("Press enter to continue.")
            print("'Do you still think your choice matters?'")
        elif ans1=="No":
            print("'You let the coin fall to the ground.'")
            input("Press enter to continue.")
            print("'The cat seemed to shrug. It is your choice after all, the cat spoke in your head. Best of luck on your journey.'")
            input("Press enter to continue.")
            print("'The cat disappeared in front of you - leaving a gaping hole.'")
            input("Press enter to continue.")
            print("'You approach the hole.'")
            input("Press enter to continue.")
            print("'Below was pitch black.'")
            input("Press enter to continue.")
            print("'You feel a strange urge to jump. Ignoring all bounds in logic you jump.'")
            input("'Press enter to continue.'")
            print("'You jump in. You end up splashing in a body of murky water. It smelled like sewage and you assumed it was.'")
            input("Press enter to continue.")
            print("'The water barely reached your knees. You waddled ahead looking for something besides endless water and darkness.'")
            input("Press enter to continue.")
            print("'All of a sudden you see a boat ahead of you.'")
            input("Press enter to continue.")
            print("'You scream trying to attract the attention of anyone on the boat.'")
            input("Press enter to continue.")
            print("'A robed figure came over to you with the boat.'")
            input("Press enter to continue.")
            print("'Do you have a coin?' The robed figure asks you.")
            input("Press enter to continue.")
            print("'You shake your head.'")
            input("Press enter to continue.")
            print("'The figure removes its hood. You see the face of the cat again with its grin.'")
            input("Press enter to continue.")
            print("'Do you still think your choice matters?'")
    elif ans=="No":
        print("'Then I suppose it doesn't really matter. But tell me, will you take this coin?'")
        input("Press enter to continue.")
        print("'A coin appears in front of you floating in mid-air.'")
        input("Press enter to continue.")
        print("Do you take the coin?'")
        ans1=input("Amswer Yes or No.")
        if ans1=="Yes":
            print("'You reach for the coin in mid air and grab it.'")
            input("Press enter to continue.")
            print("'The coin felt warm in your hands. You turned it around to see your face stamped on it.'")
            input("Press enter to continue.")
            print("'This would help you pass in your journey.'")
            input("Press enter to continue.")
            print("'You look towards where the cat was but it vanished leaving a gaping hole where it was standing. You approached the hole, looking down.'")
            input("Press enter to continue.")
            print("'Below was pitch black.'")
            input("Press enter to continue.")
            print("'You feel a strange urge to jump. Ignoring all bounds in logic you jump.'")

            print("'You jump in. You end up splashing in a body of murky water. It smelled like sewage and you assumed it was.'")
            input("Press enter to continue.")
            print("'The water barely reached your knees. You waddled ahead looking for something besides endless water and darkness.'")
            input("Press enter to continue.")
            print("'All of a sudden you see a boat ahead of you.'")
            input("Press enter to continue.")
            print("'You scream trying to attract the attention of anyone on the boat.'")
            input("Press enter to continue.")
            print("'A robed figure came over to you with the boat.'")
            input("Press enter to continue.")
            print("'Do you have a coin?' The robed figure asks you.")
            input("Press enter to continue.")
            print("'You hand the coin to the figure.'")
            input("Press enter to continue.")
            print("'With a curt nod the figure reached out a boney hand and helped you climb the boat.'")
            input("Press enter to continue.")
            print("'You crossed the river with the robed figure.'")
            input("Press enter to continue.")
            print("'Do you still think your choice matters?'")
        elif ans1=="No":
            print("'You let the coin fall to the ground.'")
            input("Press enter to continue.")
            print("'The cat seemed to shrug. It is your choice after all, the cat spoke in your head. Best of luck on your journey.'")
            input("Press enter to continue.")
            print("'The cat disappeared in front of you - leaving a gaping hole.'")
            input("Press enter to continue.")
            print("'You approach the hole.'")
            input("Press enter to continue.")
            print("'Below was pitch black.'")
            input("Press enter to continue.")
            print("'You feel a strange urge to jump. Ignoring all bounds in logic you jump.'")
            input("'Press enter to continue.'")
            print("'You jump in. You end up splashing in a body of murky water. It smelled like sewage and you assumed it was.'")
            input("Press enter to continue.")
            print("'The water barely reached your knees. You waddled ahead looking for something besides endless water and darkness.'")
            input("Press enter to continue.")
            print("'All of a sudden you see a boat ahead of you.'")
            input("Press enter to continue.")
            print("'You scream trying to attract the attention of anyone on the boat.'")
            input("Press enter to continue.")
            print("'A robed figure came over to you with the boat.'")
            input("Press enter to continue.")
            print("'Do you have a coin?' The robed figure asks you.")
            input("Press enter to continue.")
            print("'You shake your head.'")
            input("Press enter to continue.")
            print("'The figure removes its hood. You see the face of the cat again with its grin.'")
            input("Press enter to continue.")
            print("'Do you still think your choice matters?'")
else:
    print("'You stand there for all eternity waiting for something to happen.'")

